# Generated by Django 3.1 on 2020-09-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id_datos', models.AutoField(primary_key=True, serialize=False)),
                ('afectados', models.CharField(max_length=30)),
                ('duplicidad_dias', models.CharField(max_length=30)),
                ('fallecidos', models.CharField(max_length=30)),
                ('casos_ultimos', models.CharField(max_length=30)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ciudad')),
            ],
        ),
    ]
