# Generated by Django 3.1 on 2020-09-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_dpto', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Chacovid_departamentos',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_datos', models.AutoField(primary_key=True, serialize=False)),
                ('afectados', models.CharField(max_length=30)),
                ('duplicidad_dias', models.CharField(max_length=30)),
                ('fallecidos', models.CharField(max_length=30)),
                ('casos_ultimos', models.CharField(max_length=30)),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChacovidApp.departamentos')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'db_table': 'Chacovid_datos',
            },
        ),
    ]
